### ISSUE TITLE
Правильные названия методов

### ISSUE THREAD

**Issue by ZagirNur** [flashxxx2/demo#3]
Почти все методы называются неправильно.
должно быть так: get[название ресурса][условия, например по каким полям выборка]

неправильно:
    public TeacherEntity getByIdTeachersOrEmpty(Integer id) {
правильно:
    public TeacherEntity getTeacherByIdOrEmpty(Integer teacherId) {

неправильно:
    public List<GroupSubjectEntity> getListSubjectEntityByIdGroup(Integer id) {
правильно:
    public List<GroupSubjectEntity> getGroupSubjectListByGroupId(Integer groupId) {

**Comment by flashxxx2** [comment]
Исправил
